name: javascript CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x, 18.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Node.js ${{ matrix.node_version}}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version}}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run tests
      run: node test_money.js
      shell: bash
    